#!/bin/bash

# Automated OTA Update Script for Akariza Mobile App
# Usage: ./auto-update.sh [branch] [message]
# Example: ./auto-update.sh production "Fix: critical bug fix"

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
BRANCH=${1:-production}
MESSAGE=${2:-"OTA Update"}
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Functions
print_header() {
  echo -e "${BLUE}========================================${NC}"
  echo -e "${BLUE}$1${NC}"
  echo -e "${BLUE}========================================${NC}"
}

print_success() {
  echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
  echo -e "${RED}❌ $1${NC}"
}

print_warning() {
  echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
  echo -e "${BLUE}ℹ️  $1${NC}"
}

# Check prerequisites
check_prerequisites() {
  print_header "Checking Prerequisites"

  # Check if eas-cli is installed
  if ! command -v eas &> /dev/null; then
    print_error "EAS CLI not found. Install with: npm install -g eas-cli"
    exit 1
  fi
  print_success "EAS CLI found"

  # Check if logged in
  if ! eas whoami &> /dev/null; then
    print_error "Not logged in to Expo. Run: eas login"
    exit 1
  fi
  print_success "Logged in to Expo"

  # Check if git is available
  if ! command -v git &> /dev/null; then
    print_error "Git not found"
    exit 1
  fi
  print_success "Git found"
}

# Validate branch
validate_branch() {
  print_header "Validating Branch"

  case $BRANCH in
    production|staging|development)
      print_success "Branch: $BRANCH"
      ;;
    *)
      print_error "Invalid branch: $BRANCH"
      print_info "Valid branches: production, staging, development"
      exit 1
      ;;
  esac
}

# Check git status
check_git_status() {
  print_header "Checking Git Status"

  if [ -z "$(git status --porcelain)" ]; then
    print_success "Working directory clean"
  else
    print_warning "Uncommitted changes detected"
    git status --short
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      print_error "Update cancelled"
      exit 1
    fi
  fi
}

# Get current version
get_version() {
  grep '"version"' app.json | head -1 | sed 's/.*"version": "\(.*\)".*/\1/'
}

# Get git info
get_git_info() {
  COMMIT_HASH=$(git rev-parse --short HEAD)
  COMMIT_MESSAGE=$(git log -1 --pretty=%B)
  BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
}

# Display update info
display_update_info() {
  print_header "Update Information"

  VERSION=$(get_version)
  get_git_info

  echo "App Version:      $VERSION"
  echo "Update Branch:    $BRANCH"
  echo "Git Branch:       $BRANCH_NAME"
  echo "Commit Hash:      $COMMIT_HASH"
  echo "Commit Message:   $COMMIT_MESSAGE"
  echo "Update Message:   $MESSAGE"
  echo "Timestamp:        $TIMESTAMP"
}

# Confirm update
confirm_update() {
  print_header "Confirmation"

  echo "Ready to publish OTA update?"
  read -p "Continue? (y/n) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_error "Update cancelled"
    exit 1
  fi
}

# Publish update
publish_update() {
  print_header "Publishing Update"

  print_info "Publishing to $BRANCH branch..."
  
  if eas update --branch $BRANCH; then
    print_success "Update published successfully!"
  else
    print_error "Update failed"
    exit 1
  fi
}

# Get update status
get_update_status() {
  print_header "Update Status"

  print_info "Fetching latest updates..."
  eas update:list --branch $BRANCH --limit 5
}

# Create update log
create_update_log() {
  print_header "Creating Update Log"

  LOG_FILE="update-log-$(date '+%Y%m%d-%H%M%S').txt"

  cat > "$LOG_FILE" << EOF
=== OTA Update Log ===
Timestamp: $TIMESTAMP
Branch: $BRANCH
Version: $(get_version)
Commit: $COMMIT_HASH
Message: $MESSAGE

Git Commit Message:
$COMMIT_MESSAGE

Update Status:
Published to $BRANCH branch
Users will receive update on next app open

---
Generated by auto-update.sh
EOF

  print_success "Update log saved to $LOG_FILE"
}

# Send notification (optional)
send_notification() {
  print_header "Notifications"

  # You can add webhook notifications here
  # Example: Send to Slack, Discord, etc.

  print_info "Update published to $BRANCH"
  print_info "Users will receive update on next app open"
}

# Main execution
main() {
  print_header "Akariza Mobile App - OTA Update"

  check_prerequisites
  validate_branch
  check_git_status
  display_update_info
  confirm_update
  publish_update
  get_update_status
  create_update_log
  send_notification

  print_header "Update Complete!"
  print_success "OTA update published successfully"
  print_info "Branch: $BRANCH"
  print_info "Users will receive update on next app open"
}

# Run main function
main
